package com.kamsiob.meedwell

import android.os.Bundle
import android.provider.Settings
import android.view.View
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.compose.runtime.getValue
import androidx.compose.runtime.produceState
import androidx.activity.enableEdgeToEdge
import androidx.compose.runtime.Composable
import androidx.compose.runtime.remember
import androidx.compose.ui.platform.LocalContext
import androidx.lifecycle.viewmodel.compose.viewModel
import com.kamsiob.meedwell.ui.MeedwellApp
import com.kamsiob.meedwell.ui.MeedwellViewModel
import com.kamsiob.meedwell.ui.theme.MeedwellTheme

/**
 * Single activity, as specified. Everything else is Compose.
 *
 * `configChanges` in the manifest keeps rotation from recreating the activity,
 * which is the cheapest way to satisfy "every screen survives rotation without
 * losing state". Version one is portrait-first: rotation must not lose
 * anything, but no landscape-specific layouts are designed.
 */
class MainActivity : ComponentActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        enableEdgeToEdge()

        // Meedwell does not take part in autofill, anywhere in the app.
        //
        // Found on the device rather than in review: after connecting, Android
        // offered to save the Bandcamp credentials to Google Password Manager,
        // which would copy them to Google's cloud. The screen immediately above
        // that dialog says "Stored only on this phone, encrypted". Both cannot
        // be true, and the copy is the promise, so the platform behavior is
        // what changes.
        //
        // A user who wants a password manager still has one: the credentials
        // are generated by Bandcamp and live on Bandcamp's own settings page,
        // and the Paste chips exist precisely so they can be pasted from
        // wherever the user keeps them. Recorded in DECISIONS.md.
        window.decorView.importantForAutofill =
            View.IMPORTANT_FOR_AUTOFILL_NO_EXCLUDE_DESCENDANTS

        setContent {
            val container = (application as MeedwellApplication).container
            val viewModel: MeedwellViewModel = viewModel(
                factory = MeedwellViewModel.Factory(container)
            )
            viewModelRef = viewModel

            /*
             * The theme, watched rather than read.
             *
             * This was `container.settings.theme` read once inside setContent,
             * which is not Compose state, so nothing recomposed when it
             * changed. Settings showed the new value and the app stayed the old
             * color until it was killed and reopened, which reads as the
             * control being broken rather than delayed. It is also the setting
             * somebody is most likely to try first.
             */
            val theme by produceState(container.settings.theme) {
                container.settings.observeChanges().collect { value = container.settings.theme }
            }

            MeedwellTheme(
                themeChoice = theme,
                reducedMotion = rememberReducedMotion(),
            ) {
                MeedwellApp(viewModel)
            }
        }
    }

    /**
     * Held so `onResume` can ask it to sync.
     *
     * The previous version of this method read a property and discarded it. Its
     * comment described a sync on resume that did not exist, which meant a
     * record bought this morning never appeared until the account was
     * disconnected and reconnected.
     */
    private var viewModelRef: MeedwellViewModel? = null

    override fun onResume() {
        super.onResume()
        // On resume, and only if the last sync is old. Nothing runs in the
        // background hoping to be useful.
        viewModelRef?.syncIfStale()
    }
}

/**
 * Reads the system's reduced motion preference.
 *
 * `DESIGN.md` section 10 requires it to be respected everywhere: no drift on
 * the ambient washes, no shimmer on waiting tiles, and a static waveform
 * envelope. Read once here and provided through the theme, so a new animated
 * surface cannot forget to ask.
 */
@Composable
private fun rememberReducedMotion(): Boolean {
    val context = LocalContext.current
    return remember(context) {
        Settings.Global.getFloat(
            context.contentResolver,
            Settings.Global.ANIMATOR_DURATION_SCALE,
            1f,
        ) == 0f
    }
}
